name: '[X] Release-please'
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  RELEASE_BRANCH: nx-release-please

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Echo test 1
        run: echo "prepare"

  test-1:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Echo test 1
        run: echo "test 1"

  test-2:
    runs-on: ubuntu-latest
    if: false
    needs: prepare
    steps:
      - name: Echo test 2
        run: echo "test 2"


  check:
    runs-on: ubuntu-latest
    needs: 
      - prepare
      - test-1
    if: always() && needs.prepare.result == 'success' && (needs.*.result == 'skipped' || needs.*.result == 'success')
    steps:
      - name: Echo check
        run: |
         echo ${{ needs.test-1.result }}

  result:
    runs-on: ubuntu-latest
    needs: 
      - test-1
      - test-2
    if: always() && needs.prepare.result == 'success' && (needs.*.result == 'skipped' || needs.*.result == 'success')
    steps:
      - name: Echo result
        run: echo "result"
  
  summary:
    runs-on: ubuntu-latest
    needs: 
      - prepare
      - test-1
      - test-2
      - result
    if: always() && needs.prepare.result == 'success' && (needs.*.result == 'skipped' || needs.*.result == 'success')
    steps:
      - name: Echo summary
        run: echo "summary"